1_1__A_GigabitEthernet0/1_OUTBOUND_SOFTAdd -> true
0_dst-port -> 0
0_AOSPFExportRemoveSoft105.0.0.0/8 -> true
0_AOSPFExportRemoveSoft104.0.0.0/8 -> true
0_0__A_GigabitEthernet0/4_OUTBOUND_SOFTAdd -> true
0_0__C_GigabitEthernet0/1_INBOUND_SOFTAdd -> true
1_1__B_GigabitEthernet0/3_INBOUND_SOFTAdd -> true
0_src-port -> 0
0_C-StaticRouteAdd-C,GigabitEthernet0/1 --> B,GigabitEthernet0/2 -> false
0_B-StaticRouteAdd-B,GigabitEthernet0/2 --> C,GigabitEthernet0/1 -> false
0_A_OSPF_IMPORT_GigabitEthernet0/1_metric -> 2
0_C_OSPF_SINGLE-EXPORT__metric -> 0
0_CONTROL-FORWARDING_A_GigabitEthernet0/1 -> false
0_CONTROL-FORWARDING_C_GigabitEthernet0/1 -> false
0__reachable-id_A -> 0
1_1__A_GigabitEthernet0/1_INBOUND_SOFTAdd -> true
1_1__C_GigabitEthernet0/1_INBOUND_SOFTAdd -> true
0_B_OSPF_IMPORT_GigabitEthernet0/1_metric -> 2
0_AImportFilterAddSoft0_A_OSPF_IMPORT_GigabitEthernet0/2 -> true
0_CONTROL-FORWARDING_C_GigabitEthernet0/2 -> false
0_A_OSPF_IMPORT_GigabitEthernet0/2_prefixLength -> 8
0_B_OSPF_SINGLE-EXPORT__prefixLength -> 8
1_1__A_GigabitEthernet0/2_OUTBOUND_SOFTAdd -> true
0_B_OSPF_SINGLE-EXPORT__metric -> 1
0_A_OVERALL_BEST_None_prefixLength -> 8
0_C_OSPF_SoftRedistributed_metric -> 1
0_0__A_GigabitEthernet0/3_INBOUND_SOFTAdd -> true
0_0__A_GigabitEthernet0/3_OUTBOUND_SOFTAdd -> true
0_icmp-code -> 0
0_A-StaticRouteAdd-A,GigabitEthernet0/1 --> B,GigabitEthernet0/1 -> false
0_AOSPFExportRemoveSoft1.0.0.0/16 -> true
0_C_OSPF_IMPORT_GigabitEthernet0/2_metric -> 2
0_0__C_GigabitEthernet0/3_OUTBOUND_SOFTAdd -> true
0_0__C_GigabitEthernet0/2_OUTBOUND_SOFTAdd -> true
0_C-StaticRouteAdd-C,GigabitEthernet0/2 --> A,GigabitEthernet0/2 -> false
1_1__C_GigabitEthernet0/3_INBOUND_SOFTAdd -> true
0_C_OSPF_IMPORT_GigabitEthernet0/1_permitted -> true
1_1__B_GigabitEthernet0/2_INBOUND_SOFTAdd -> true
0_A-StaticRouteAdd-A,GigabitEthernet0/2 --> C,GigabitEthernet0/2 -> false
0_B-StaticRouteAdd-B,GigabitEthernet0/1 --> A,GigabitEthernet0/1 -> false
0_CONTROL-FORWARDING_B_GigabitEthernet0/2 -> true
0_0__B_GigabitEthernet0/1_INBOUND_SOFTAdd -> true
0_AOSPFExportRemoveSoft3.0.0.0/16 -> true
1_1__A_GigabitEthernet0/2_INBOUND_SOFTAdd -> true
0_A_OVERALL_BEST_None_metric -> 1
0_A_OSPF_SINGLE-EXPORT__prefixLength -> 8
0_B_OSPF_IMPORT_GigabitEthernet0/2_prefixLength -> 8
0_B_OVERALL_BEST_None_prefixLength -> 8
0_0__A_GigabitEthernet0/1_INBOUND_SOFTAdd -> true
0_icmp-type -> 0
1_1__A_GigabitEthernet0/4_OUTBOUND_SOFTAdd -> true
1_1__B_GigabitEthernet0/3_OUTBOUND_SOFTAdd -> true
1_1__B_GigabitEthernet0/1_OUTBOUND_SOFTAdd -> true
0_B_OSPF_IMPORT_GigabitEthernet0/2_permitted -> true
0_C_OVERALL_BEST_None_history -> #b1
0_BOSPFExportAddSoft106.0.0.0/8 -> false
0_CONTROL-FORWARDING_A_GigabitEthernet0/2 -> true
0_A_OSPF_IMPORT_GigabitEthernet0/2_metric -> 1
1_1__B_GigabitEthernet0/2_OUTBOUND_SOFTAdd -> true
0_0__C_GigabitEthernet0/1_OUTBOUND_SOFTAdd -> true
1_1__C_GigabitEthernet0/2_INBOUND_SOFTAdd -> false
0_COSPFExportRemoveSoft3.0.0.0/16 -> true
0_0__B_GigabitEthernet0/2_OUTBOUND_SOFTAdd -> true
0_A_OSPF_SINGLE-EXPORT__permitted -> true
0_0__B_GigabitEthernet0/2_INBOUND_SOFTAdd -> true
1_1__C_GigabitEthernet0/3_OUTBOUND_SOFTAdd -> true
0_AImportFilterAddSoft0_A_OSPF_IMPORT_GigabitEthernet0/1 -> true
1_1__A_GigabitEthernet0/3_OUTBOUND_SOFTAdd -> true
0_A_OSPF_IMPORT_GigabitEthernet0/1_prefixLength -> 8
1_icmp-type -> 0
0_B_OSPF_SINGLE-EXPORT__permitted -> true
1_1__A_GigabitEthernet0/3_INBOUND_SOFTAdd -> true
0_0__A_GigabitEthernet0/2_INBOUND_SOFTAdd -> true
0_C_OSPF_SoftRedistributed_prefixLength -> 1
0_0__B_GigabitEthernet0/3_OUTBOUND_SOFTAdd -> true
0_CImportFilterAddSoft0_C_OSPF_IMPORT_GigabitEthernet0/2 -> true
1_icmp-code -> 0
1_1__B_GigabitEthernet0/1_INBOUND_SOFTAdd -> true
1_src-port -> 0
0_0__A_GigabitEthernet0/2_OUTBOUND_SOFTAdd -> true
0_0__A_GigabitEthernet0/1_OUTBOUND_SOFTAdd -> true
0_BOSPFExportRemoveSoft2.0.0.0/16 -> true
0_C_OSPF_SINGLE-EXPORT__prefixLength -> 8
0_COSPFExportRemoveSoft103.0.0.0/8 -> true
0_CImportFilterAddSoft0_C_OSPF_IMPORT_GigabitEthernet0/1 -> true
0_C_OSPF_IMPORT_GigabitEthernet0/1_metric -> 2
0__reachable-id_B -> 2
0_A_OSPF_SINGLE-EXPORT__metric -> 1
0_BOSPFExportRemoveSoft1.0.0.0/16 -> true
0_C_OVERALL_BEST_None_prefixLength -> 8
0_C_OSPF_BEST_None_prefixLength -> 8
0_C_OSPF_IMPORT_GigabitEthernet0/2_permitted -> true
0_C_OSPF_IMPORT_GigabitEthernet0/1_prefixLength -> 8
1__reachable-id_A -> 0
0_0__B_GigabitEthernet0/3_INBOUND_SOFTAdd -> true
0_0__C_GigabitEthernet0/3_INBOUND_SOFTAdd -> true
0_C_OSPF_IMPORT_GigabitEthernet0/2_prefixLength -> 8
0_0__B_GigabitEthernet0/1_OUTBOUND_SOFTAdd -> true
0_B_OSPF_IMPORT_GigabitEthernet0/2_metric -> 1
0_C_OSPF_BEST_None_metric -> 2
0_C_OSPF_SoftRedistributed_permitted -> true
0_B_OVERALL_BEST_None_metric -> 1
0_C_OSPF_SINGLE-EXPORT__permitted -> true
0_C_OVERALL_BEST_None_adminDist -> 0
0_C_OVERALL_BEST_None_metric -> 0
0_A_OSPF_IMPORT_GigabitEthernet0/2_permitted -> true
0_A_OSPF_IMPORT_GigabitEthernet0/1_permitted -> true
1_dst-port -> 0
1__reachable-id_B -> 2
0_COSPFExportRemoveSoft2.0.0.0/16 -> true
1_1__C_GigabitEthernet0/2_OUTBOUND_SOFTAdd -> true
0_B_OSPF_IMPORT_GigabitEthernet0/1_permitted -> true
0_0__C_GigabitEthernet0/2_INBOUND_SOFTAdd -> false
0_0__A_GigabitEthernet0/4_INBOUND_SOFTAdd -> true
0_BImportFilterAddSoft0_B_OSPF_IMPORT_GigabitEthernet0/1 -> true
0_BImportFilterAddSoft0_B_OSPF_IMPORT_GigabitEthernet0/2 -> true
1_1__C_GigabitEthernet0/1_OUTBOUND_SOFTAdd -> true
0_CONTROL-FORWARDING_B_GigabitEthernet0/1 -> false
1_1__A_GigabitEthernet0/4_INBOUND_SOFTAdd -> true
0_B_OSPF_IMPORT_GigabitEthernet0/1_prefixLength -> 8
0_C_CONNECTED_IMPORT_GigabitEthernet0/3_prefixLength -> 8
1__reachable-id_C -> 1
1__reachable_C -> true
1__reachable_B -> true
1__reachable_A -> false
1_src-ip -> #x69000104
1_dst-ip -> #x67000303
1_DATA-FORWARDING_C_GigabitEthernet0/1 -> false
1_DATA-FORWARDING_C_GigabitEthernet0/2 -> false
1_DATA-FORWARDING_C_GigabitEthernet0/3 -> false
1_DATA-FORWARDING_B_GigabitEthernet0/3 -> false
1_DATA-FORWARDING_B_GigabitEthernet0/2 -> true
1_DATA-FORWARDING_B_GigabitEthernet0/1 -> false
1_DATA-FORWARDING_A_GigabitEthernet0/1 -> false
1_DATA-FORWARDING_A_GigabitEthernet0/4 -> false
1_DATA-FORWARDING_A_GigabitEthernet0/3 -> false
1_DATA-FORWARDING_A_GigabitEthernet0/2 -> true
0__reachable-id_C -> 1
0__reachable_C -> true
0__reachable_B -> true
0__reachable_A -> false
0_src-ip -> #x68000103
0_dst-ip -> #x67000303
0_DATA-FORWARDING_C_GigabitEthernet0/1 -> false
0_DATA-FORWARDING_C_GigabitEthernet0/2 -> false
0_DATA-FORWARDING_C_GigabitEthernet0/3 -> false
0_DATA-FORWARDING_B_GigabitEthernet0/3 -> false
0_DATA-FORWARDING_B_GigabitEthernet0/2 -> true
0_DATA-FORWARDING_B_GigabitEthernet0/1 -> false
0_DATA-FORWARDING_A_GigabitEthernet0/1 -> false
0_DATA-FORWARDING_A_GigabitEthernet0/4 -> false
0_DATA-FORWARDING_A_GigabitEthernet0/3 -> false
0_DATA-FORWARDING_A_GigabitEthernet0/2 -> true
0_CONTROL-FORWARDING_C_GigabitEthernet0/3 -> false
0_CONTROL-FORWARDING_B_GigabitEthernet0/3 -> false
0_CONTROL-FORWARDING_A_GigabitEthernet0/4 -> false
0_CONTROL-FORWARDING_A_GigabitEthernet0/3 -> false
0_C_OVERALL_BEST_None_permitted -> true
0_C_CONNECTED_IMPORT_GigabitEthernet0/3_choice -> true
0_C_OSPF_IMPORT_GigabitEthernet0/2_choice -> true
0_C_OSPF_IMPORT_GigabitEthernet0/1_choice -> true
0_B_OSPF_IMPORT_GigabitEthernet0/2_choice -> true
0_B_OSPF_IMPORT_GigabitEthernet0/1_choice -> false
0_A_OSPF_IMPORT_GigabitEthernet0/1_choice -> false
0_A_OSPF_IMPORT_GigabitEthernet0/2_choice -> true
0_C_CONNECTED_BEST_None_permitted -> true
0_C_CONNECTED_BEST_None_prefixLength -> 8
0_C_OSPF_BEST_None_permitted -> true
0_B_OVERALL_BEST_None_permitted -> true
0_A_OVERALL_BEST_None_permitted -> true
0_C_CONNECTED_IMPORT_GigabitEthernet0/3_permitted -> true
0_FAILED-EDGE_A_GigabitEthernet0/4 -> 0
0_FAILED-EDGE_B_GigabitEthernet0/3 -> 0
0_FAILED-EDGE_C_GigabitEthernet0/3 -> 0
0_FAILED-EDGE_B_C -> 0
0_FAILED-EDGE_A_GigabitEthernet0/3 -> 0
0_FAILED-EDGE_A_C -> 0
0_FAILED-EDGE_A_B -> 0
