0_dst-port -> 0
0_CONTROL-FORWARDING_R3_Serial0 -> true
0__reachable-id_R2 -> 2
0_R2_OVERALL_BEST_None_routerID -> 707406337
0_R1_BGP_BEST_None_prefixLength -> 24
0_src-port -> 0
0_R3-StaticRouteAdd-R3,Serial0 --> R2,Serial1 -> false
0_0__R2_Serial0_INBOUND_SOFTAdd -> true
0_0__R2_Serial1_INBOUND_SOFTAdd -> true
0_0_R3_OVERALL_BEST_NoneBGPExportAddSoft -> false
0_0__R1_Loopback0_INBOUND_SOFTAdd -> true
0_R3_OVERALL_BEST_None_routerID -> 1162167553
0_R1_BGP_SINGLE-EXPORT__metric -> 1
0_CONTROL-FORWARDING_R2_Serial0 -> true
0_R3_BGP_SINGLE-EXPORT__metric -> 3
0_R1_BGP_SINGLE-EXPORT__prefixLength -> 24
0_0_R2_OVERALL_BEST_NoneBGPExportAddSoft -> false
0_0__R2_Loopback0_OUTBOUND_SOFTAdd -> true
0_0__R1_Serial0_INBOUND_SOFTAdd -> true
0_R2_BGP_SINGLE-EXPORT__metric -> 2
0_icmp-code -> 0
0_0__R3_Serial0_INBOUND_SOFTAdd -> true
0_R3_OVERALL_BEST_None_permitted -> true
0_R1_OVERALL_BEST_None_adminDist -> 0
0_0__R2_Serial0_OUTBOUND_SOFTAdd -> true
0_0__R1_Loopback1_OUTBOUND_SOFTAdd -> true
0_CONTROL-FORWARDING_R2_Serial1 -> false
0_R1_OVERALL_BEST_None_routerID -> 0
0_R3_BGP_SINGLE-EXPORT__prefixLength -> 24
0_R3_BGP_SINGLE-EXPORT__permitted -> true
0_R2-StaticRouteAdd-R2,Serial0 --> R1,Serial0 -> false
0_R1_BGP_SINGLE-EXPORT__permitted -> true
0_R2_OVERALL_BEST_None_prefixLength -> 24
0_0__R1_Loopback1_INBOUND_SOFTAdd -> true
0_0_R1_OVERALL_BEST_NoneBGPExportAddSoft -> true
0_0__R3_Loopback0_OUTBOUND_SOFTAdd -> true
0_R2-StaticRouteAdd-R2,Serial1 --> R3,Serial0 -> false
0_0__R2_Serial1_OUTBOUND_SOFTAdd -> true
0_icmp-type -> 0
0_R3_OVERALL_BEST_None_prefixLength -> 24
0_R2_BGP_SINGLE-EXPORT__prefixLength -> 24
0_42.42.42.0/24Stat-Conn-ExportRemoveSoft0_R1_OVERALL_BEST_None -> true
0_R1-StaticRouteAdd-R1,Serial0 --> R2,Serial0 -> false
0_R1_OVERALL_BEST_None_metric -> 0
0_R3_OVERALL_BEST_None_metric -> 2
0_R1_BGP_BEST_None_routerID -> 1162167553
0_R1_BGP_BEST_None_metric -> 2
0_0__R1_Loopback0_OUTBOUND_SOFTAdd -> true
0__reachable-id_R3 -> 3
0_CONTROL-FORWARDING_R1_Serial0 -> false
0_0__R2_Loopback0_INBOUND_SOFTAdd -> true
0_R2_OVERALL_BEST_None_metric -> 1
0_R1_OVERALL_BEST_None_history -> #b1
0_0__R1_Serial0_OUTBOUND_SOFTAdd -> true
0_0__R3_Serial0_OUTBOUND_SOFTAdd -> true
0_0__R3_Loopback0_INBOUND_SOFTAdd -> true
0_ip-protocol -> 0
0_R1_OVERALL_BEST_None_prefixLength -> 24
0_69.69.69.0/24OSPF-ExportRemoveSoft0_R2_OVERALL_BEST_None -> true
0_R1_CONNECTED_IMPORT_Loopback1_prefixLength -> 24
0__reachable_R1 -> true
0__reachable_R3 -> true
0__reachable_R2 -> true
0__reachable-id_R1 -> 1
0_src-ip -> #x4f4f4f01
0_dst-ip -> #x16161601
0_DATA-FORWARDING_R1_Loopback0 -> false
0_DATA-FORWARDING_R1_Loopback1 -> false
0_DATA-FORWARDING_R1_Serial0 -> false
0_DATA-FORWARDING_R3_Serial0 -> true
0_DATA-FORWARDING_R3_Loopback0 -> false
0_DATA-FORWARDING_R2_Serial0 -> true
0_DATA-FORWARDING_R2_Serial1 -> false
0_DATA-FORWARDING_R2_Loopback0 -> false
0_CONTROL-FORWARDING_R1_Loopback1 -> false
0_CONTROL-FORWARDING_R1_Loopback0 -> false
0_CONTROL-FORWARDING_R3_Loopback0 -> false
0_CONTROL-FORWARDING_R2_Loopback0 -> false
0_R1_OVERALL_BEST_None_permitted -> true
0_R1_CONNECTED_IMPORT_Loopback1_choice -> true
0_R1_BGP_IMPORT_Serial0_choice -> true
0_R3_BGP_IMPORT_Serial0_choice -> true
0_R2_BGP_IMPORT_Serial0_choice -> true
0_R2_BGP_IMPORT_Serial1_choice -> false
0_R1_CONNECTED_BEST_None_permitted -> true
0_R1_CONNECTED_BEST_None_prefixLength -> 24
0_R1_BGP_BEST_None_permitted -> true
0_R2_BGP_SINGLE-EXPORT__permitted -> true
0_R2_OVERALL_BEST_None_permitted -> true
0_R1_CONNECTED_IMPORT_Loopback1_permitted -> true
0_FAILED-EDGE_R1_Loopback0 -> 0
0_FAILED-EDGE_R3_Loopback0 -> 0
0_FAILED-EDGE_R1_R2 -> 0
0_FAILED-EDGE_R1_Loopback1 -> 0
0_FAILED-EDGE_R2_Loopback0 -> 0
0_FAILED-EDGE_R2_R3 -> 0
