0_FAILED-EDGE_A_B -> 0
0_FAILED-EDGE_B_C -> 0
0_0__B_GigabitEthernet0/2_OUTBOUND_SOFTAdd -> true
0_dst-port -> 0
0_A_OSPF_IMPORT_GigabitEthernet0/1_prefixLength -> 8
0_AOSPFExportRemoveSoft104.0.0.0/8 -> true
0_A_OSPF_BEST_None_permitted -> true
0_AImportFilterAddSoft0_A_OSPF_IMPORT_GigabitEthernet0/1 -> true
0_0__B_GigabitEthernet0/2_INBOUND_SOFTAdd -> true
0_0__C_GigabitEthernet0/1_INBOUND_SOFTAdd -> true
0_AOSPFExportRemoveSoft105.0.0.0/8 -> true
0_0__A_GigabitEthernet0/4_OUTBOUND_SOFTAdd -> true
0_C-StaticRouteAdd-C,GigabitEthernet0/1 --> B,GigabitEthernet0/2 -> false
0_B-StaticRouteAdd-B,GigabitEthernet0/2 --> C,GigabitEthernet0/1 -> false
0_src-port -> 0
0_A_OSPF_BEST_None_metric -> 2
0_CONTROL-FORWARDING_A_GigabitEthernet0/1 -> false
0_CONTROL-FORWARDING_C_GigabitEthernet0/1 -> true
0_0__B_GigabitEthernet0/3_OUTBOUND_SOFTAdd -> true
0_A_OSPF_IMPORT_GigabitEthernet0/1_metric -> 2
0_C_OSPF_EXPORT_GigabitEthernet0/1_prefixLength -> 8
0_A_OVERALL_BEST_None_history -> #b1
0_A_OSPF_EXPORT_GigabitEthernet0/1_permitted -> true
0_B_OSPF_IMPORT_GigabitEthernet0/1_metric -> 1
0_A_OSPF_BEST_None_prefixLength -> 8
0_B_OSPF_EXPORT_GigabitEthernet0/1_prefixLength -> 8
0_A_OVERALL_BEST_None_adminDist -> 0
0_C_OSPF_IMPORT_GigabitEthernet0/1_metric -> 2
0_BOSPFExportRemoveSoft2.0.0.0/16 -> true
0_0__A_GigabitEthernet0/1_OUTBOUND_SOFTAdd -> true
0__reachable-id_B -> 2
0_COSPFExportRemoveSoft103.0.0.0/8 -> true
0_CImportFilterAddSoft0_C_OSPF_IMPORT_GigabitEthernet0/1 -> true
0_B_OSPF_EXPORT_GigabitEthernet0/1_permitted -> true
0_A_OVERALL_BEST_None_prefixLength -> 8
0_BOSPFExportRemoveSoft1.0.0.0/16 -> true
0_0__A_GigabitEthernet0/3_INBOUND_SOFTAdd -> true
0_0__A_GigabitEthernet0/3_OUTBOUND_SOFTAdd -> true
0_icmp-code -> 0
0_A-StaticRouteAdd-A,GigabitEthernet0/1 --> B,GigabitEthernet0/1 -> false
0_AOSPFExportRemoveSoft1.0.0.0/16 -> true
0_C_OVERALL_BEST_None_prefixLength -> 8
0_B_OSPF_EXPORT_GigabitEthernet0/1_metric -> 1
0_C_OSPF_EXPORT_GigabitEthernet0/1_metric -> 2
0_0__C_GigabitEthernet0/3_OUTBOUND_SOFTAdd -> true
0_C_OSPF_IMPORT_GigabitEthernet0/1_prefixLength -> 8
0_C_OSPF_EXPORT_GigabitEthernet0/1_permitted -> true
0_0__B_GigabitEthernet0/3_INBOUND_SOFTAdd -> true
0_0__C_GigabitEthernet0/3_INBOUND_SOFTAdd -> true
0_B_OSPF_IMPORT_GigabitEthernet0/2_prefixLength -> 8
0_B_OSPF_EXPORT_GigabitEthernet0/2_permitted -> true
0_B-StaticRouteAdd-B,GigabitEthernet0/1 --> A,GigabitEthernet0/1 -> false
0_CONTROL-FORWARDING_B_GigabitEthernet0/2 -> false
0_0__B_GigabitEthernet0/1_INBOUND_SOFTAdd -> true
0__reachable-id_C -> 3
0_0__B_GigabitEthernet0/1_OUTBOUND_SOFTAdd -> true
0_A_OVERALL_BEST_None_metric -> 0
0_B_OSPF_IMPORT_GigabitEthernet0/2_metric -> 3
0_B_OVERALL_BEST_None_prefixLength -> 8
0_B_OVERALL_BEST_None_metric -> 1
0_0__A_GigabitEthernet0/1_INBOUND_SOFTAdd -> true
0_icmp-type -> 0
0_C_OVERALL_BEST_None_metric -> 2
0_BOSPFExportRemoveSoft106.0.0.0/8 -> true
0_B_OSPF_EXPORT_GigabitEthernet0/2_metric -> 1
0_COSPFExportRemoveSoft2.0.0.0/16 -> true
0_B_OSPF_EXPORT_GigabitEthernet0/2_prefixLength -> 8
0_B_OSPF_IMPORT_GigabitEthernet0/1_permitted -> true
0_B_OSPF_IMPORT_GigabitEthernet0/2_permitted -> true
0_A_OSPF_EXPORT_GigabitEthernet0/1_prefixLength -> 8
0_0__A_GigabitEthernet0/4_INBOUND_SOFTAdd -> true
0_BImportFilterAddSoft0_B_OSPF_IMPORT_GigabitEthernet0/1 -> true
0_BImportFilterAddSoft0_B_OSPF_IMPORT_GigabitEthernet0/2 -> true
0_C_OVERALL_BEST_None_permitted -> true
0_0__C_GigabitEthernet0/1_OUTBOUND_SOFTAdd -> true
0_ip-protocol -> 0
0_CONTROL-FORWARDING_B_GigabitEthernet0/1 -> true
0_A_OSPF_EXPORT_GigabitEthernet0/1_metric -> 0
0_B_OSPF_IMPORT_GigabitEthernet0/1_prefixLength -> 8
0_A_CONNECTED_IMPORT_GigabitEthernet0/3_prefixLength -> 8
0_FAILED-EDGE_C_GigabitEthernet0/3 -> 0
0_FAILED-EDGE_B_GigabitEthernet0/3 -> 0
0_FAILED-EDGE_A_GigabitEthernet0/4 -> 0
0_FAILED-EDGE_A_GigabitEthernet0/3 -> 0
0__reachable_C -> true
0__reachable_B -> true
0__reachable_A -> true
0__reachable-id_A -> 1
0_src-ip -> #x67000303
0_dst-ip -> #x68000103
0_DATA-FORWARDING_C_GigabitEthernet0/1 -> true
0_DATA-FORWARDING_C_GigabitEthernet0/3 -> false
0_DATA-FORWARDING_B_GigabitEthernet0/3 -> false
0_DATA-FORWARDING_B_GigabitEthernet0/2 -> false
0_DATA-FORWARDING_B_GigabitEthernet0/1 -> true
0_DATA-FORWARDING_A_GigabitEthernet0/1 -> false
0_DATA-FORWARDING_A_GigabitEthernet0/4 -> false
0_DATA-FORWARDING_A_GigabitEthernet0/3 -> false
0_CONTROL-FORWARDING_C_GigabitEthernet0/3 -> false
0_CONTROL-FORWARDING_B_GigabitEthernet0/3 -> false
0_CONTROL-FORWARDING_A_GigabitEthernet0/3 -> false
0_CONTROL-FORWARDING_A_GigabitEthernet0/4 -> false
0_A_OVERALL_BEST_None_permitted -> true
0_C_OSPF_IMPORT_GigabitEthernet0/1_choice -> true
0_B_OSPF_IMPORT_GigabitEthernet0/2_choice -> false
0_B_OSPF_IMPORT_GigabitEthernet0/1_choice -> true
0_A_CONNECTED_IMPORT_GigabitEthernet0/3_choice -> true
0_A_OSPF_IMPORT_GigabitEthernet0/1_choice -> true
0_C_OSPF_IMPORT_GigabitEthernet0/1_permitted -> true
0_B_OVERALL_BEST_None_permitted -> true
0_A_CONNECTED_BEST_None_permitted -> true
0_A_CONNECTED_BEST_None_prefixLength -> 8
0_A_OSPF_IMPORT_GigabitEthernet0/1_permitted -> true
0_A_CONNECTED_IMPORT_GigabitEthernet0/3_permitted -> true
