package org.batfish.mulgraph;

import java.io.IOException;

public class Test1 {

    public static void main(String[] args) throws IOException {

        Digraph graph = new Digraph();
        //Disconnect kconn = new Disconnect(graph);
        //Unreachable unreach = new Unreachable(graph);
        Verification vf = new Verification(graph);

        Node v1 = new Node("v1", protocol.BGP);
        Node v2 = new Node("v2", protocol.BGP);
        Node v3 = new Node("v3", protocol.BGP);
        Node v4 = new Node("v4", protocol.BGP);
        Node v5 = new Node("v5", protocol.BGP);
        Node v6 = new Node("v6", protocol.BGP);
        Node v7 = new Node("v7", protocol.BGP);
        Node v8 = new Node("v8", protocol.BGP);
        Node v9 = new Node("v9", protocol.BGP);
        Node v10 = new Node("v10", protocol.BGP);
        Node v11 = new Node("v11", protocol.BGP);
        Node v12 = new Node("v12", protocol.BGP);
        Node v13 = new Node("v13", protocol.BGP);
        Node v14 = new Node("v14", protocol.BGP);
        Node v15 = new Node("v15", protocol.BGP);
        Node v16 = new Node("v16", protocol.BGP);
        Node v17 = new Node("v17", protocol.BGP);
        Node v18 = new Node("v18", protocol.BGP);
        Node v19 = new Node("v19", protocol.BGP);
        Node v20 = new Node("v20", protocol.BGP);

        Node v21 = new Node("v21", protocol.BGP);
        Node v22 = new Node("v22", protocol.BGP);
        Node v23 = new Node("v23", protocol.BGP);
        Node v24 = new Node("v24", protocol.BGP);
        Node v25 = new Node("v25", protocol.BGP);
        Node v26 = new Node("v26", protocol.BGP);
        Node v27 = new Node("v27", protocol.BGP);
        Node v28 = new Node("v28", protocol.BGP);
        Node v29 = new Node("v29", protocol.BGP);
        Node v30 = new Node("v30", protocol.BGP);
        Node v31 = new Node("v31", protocol.BGP);
        Node v32 = new Node("v32", protocol.BGP);
        Node v33 = new Node("v33", protocol.BGP);
        Node v34 = new Node("v34", protocol.BGP);
        Node v35 = new Node("v35", protocol.BGP);
        Node v36 = new Node("v36", protocol.BGP);
        Node v37 = new Node("v37", protocol.BGP);
        Node v38 = new Node("v38", protocol.BGP);
        Node v39 = new Node("v39", protocol.BGP);
        Node v40 = new Node("v40", protocol.BGP);

        Node v41 = new Node("v41", protocol.BGP);
        Node v42 = new Node("v42", protocol.BGP);
        Node v43 = new Node("v43", protocol.BGP);
        Node v44 = new Node("v44", protocol.BGP);
        Node v45 = new Node("v45", protocol.BGP);
        Node v46 = new Node("v46", protocol.BGP);
        Node v47 = new Node("v47", protocol.BGP);
        Node v48 = new Node("v48", protocol.BGP);
        Node v49 = new Node("v49", protocol.BGP);
        Node v50 = new Node("v50", protocol.BGP);
        Node v51 = new Node("v51", protocol.BGP);
        Node v52 = new Node("v52", protocol.BGP);
        Node v53 = new Node("v53", protocol.BGP);
        Node v54 = new Node("v54", protocol.BGP);
        Node v55 = new Node("v55", protocol.BGP);
        Node v56 = new Node("v56", protocol.BGP);
        Node v57 = new Node("v57", protocol.BGP);
        Node v58 = new Node("v58", protocol.BGP);
        Node v59 = new Node("v59", protocol.BGP);
        Node v60 = new Node("v60", protocol.BGP);

        Node v61 = new Node("v61", protocol.BGP);
        Node v62 = new Node("v62", protocol.BGP);
        Node v63 = new Node("v63", protocol.BGP);
        Node v64 = new Node("v64", protocol.BGP);
        Node v65 = new Node("v65", protocol.BGP);
        Node v66 = new Node("v66", protocol.BGP);
        Node v67 = new Node("v67", protocol.BGP);
        Node v68 = new Node("v68", protocol.BGP);
        Node v69 = new Node("v69", protocol.BGP);
        Node v70 = new Node("v70", protocol.BGP);
        Node v71 = new Node("v71", protocol.BGP);
        Node v72 = new Node("v72", protocol.BGP);
        Node v73 = new Node("v73", protocol.BGP);
        Node v74 = new Node("v74", protocol.BGP);
        Node v75 = new Node("v75", protocol.BGP);
        Node v76 = new Node("v76", protocol.BGP);
        Node v77 = new Node("v77", protocol.BGP);
        Node v78 = new Node("v78", protocol.BGP);
        Node v79 = new Node("v79", protocol.BGP);
        Node v80 = new Node("v80", protocol.BGP);

        
        v19.blockCommunity("10");
        v20.blockCommunity("10");
        v21.blockCommunity("10");
        //v2.removeCommunity(10);
        v37.removeCommunity("10");
        //v21.removeCommunity(10);
        v34.addCommunity("10");
        v35.addCommunity("10");
        v36.addCommunity("10");
        //*/

        graph.add(v1);
        graph.add(v2);
        graph.add(v3);
        graph.add(v4);
        graph.add(v5);
        graph.add(v6);
        graph.add(v7);
        graph.add(v8);
        graph.add(v9);
        graph.add(v10);
        graph.add(v11);
        graph.add(v12);
        graph.add(v13);
        graph.add(v14);
        graph.add(v15);
        graph.add(v16);
        graph.add(v17);
        graph.add(v18);
        graph.add(v19);
        graph.add(v20);//*
        graph.add(v21);
        graph.add(v22);
        graph.add(v23);
        graph.add(v24);
        graph.add(v25);
        graph.add(v26);
        graph.add(v27);
        graph.add(v28);
        graph.add(v29);
        graph.add(v30);
        graph.add(v31);
        graph.add(v32);
        graph.add(v33);
        graph.add(v34);
        graph.add(v35);
        graph.add(v36);
        graph.add(v37);
        graph.add(v38);
        graph.add(v39);
        graph.add(v40);
        graph.add(v41);
        graph.add(v42);
        graph.add(v43);
        graph.add(v44);
        graph.add(v45);/*
        graph.add(v46);
        graph.add(v47);
        graph.add(v48);
        graph.add(v49);
        graph.add(v50);
        graph.add(v51);
        graph.add(v52);
        graph.add(v53);
        graph.add(v54);
        graph.add(v55);
        graph.add(v56);
        graph.add(v57);
        graph.add(v58);
        graph.add(v59);
        graph.add(v60);
        graph.add(v61);
        graph.add(v62);
        graph.add(v63);
        graph.add(v64);
        graph.add(v65);
        graph.add(v66);
        graph.add(v67);
        graph.add(v68);
        graph.add(v69);
        graph.add(v70);
        graph.add(v71);
        graph.add(v72);
        graph.add(v73);
        graph.add(v74);
        graph.add(v75);
        graph.add(v76);
        graph.add(v77);
        graph.add(v78);
        graph.add(v79);
        graph.add(v80);*/


        EdgeCost ec = new EdgeCost();
        //ec.setOSPF(1);
        ec.setAS(1);
        /*
        graph.add(v1, v9, ec, protocol.BGP);
        graph.add(v1, v10, ec, protocol.BGP);
        graph.add(v2, v9, ec, protocol.BGP);
        graph.add(v2, v10, ec, protocol.BGP);
        graph.add(v3, v11, ec, protocol.BGP);
        graph.add(v3, v12, ec, protocol.BGP);
        graph.add(v4, v11, ec, protocol.BGP);
        graph.add(v4, v12, ec, protocol.BGP);
        graph.add(v5, v13, ec, protocol.BGP);
        graph.add(v5, v14, ec, protocol.BGP);
        graph.add(v6, v13, ec, protocol.BGP);
        graph.add(v6, v14, ec, protocol.BGP);
        graph.add(v7, v15, ec, protocol.BGP);
        graph.add(v7, v16, ec, protocol.BGP);
        graph.add(v8, v15, ec, protocol.BGP);
        graph.add(v8, v16, ec, protocol.BGP);
        graph.add(v9, v17, ec, protocol.BGP);
        graph.add(v9, v18, ec, protocol.BGP);
        graph.add(v10, v19, ec, protocol.BGP);
        graph.add(v10, v20, ec, protocol.BGP);
        graph.add(v11, v17, ec, protocol.BGP);
        graph.add(v11, v18, ec, protocol.BGP);
        graph.add(v12, v19, ec, protocol.BGP);
        graph.add(v12, v20, ec, protocol.BGP);
        graph.add(v13, v17, ec, protocol.BGP);
        graph.add(v13, v18, ec, protocol.BGP);
        graph.add(v14, v19, ec, protocol.BGP);
        graph.add(v14, v20, ec, protocol.BGP);
        graph.add(v15, v17, ec, protocol.BGP);
        graph.add(v15, v18, ec, protocol.BGP);
        graph.add(v16, v19, ec, protocol.BGP);
        graph.add(v16, v20, ec, protocol.BGP);
        graph.add(v9, v1, ec, protocol.BGP);
        graph.add(v10, v1, ec, protocol.BGP);
        graph.add(v9, v2, ec, protocol.BGP);
        graph.add(v10, v2, ec, protocol.BGP);
        graph.add(v11, v3, ec, protocol.BGP);
        graph.add(v12, v3, ec, protocol.BGP);
        graph.add(v11, v4, ec, protocol.BGP);
        graph.add(v12, v4, ec, protocol.BGP);
        graph.add(v13, v5, ec, protocol.BGP);
        graph.add(v14, v5, ec, protocol.BGP);
        graph.add(v13, v6, ec, protocol.BGP);
        graph.add(v14, v6, ec, protocol.BGP);
        graph.add(v15, v7, ec, protocol.BGP);
        graph.add(v16, v7, ec, protocol.BGP);
        graph.add(v15, v8, ec, protocol.BGP);
        graph.add(v16, v8, ec, protocol.BGP);
        graph.add(v17, v9, ec, protocol.BGP);
        graph.add(v18, v9, ec, protocol.BGP);
        graph.add(v19, v10, ec, protocol.BGP);
        graph.add(v20, v10, ec, protocol.BGP);
        graph.add(v17, v11, ec, protocol.BGP);
        graph.add(v18, v11, ec, protocol.BGP);
        graph.add(v19, v12, ec, protocol.BGP);
        graph.add(v20, v12, ec, protocol.BGP);
        graph.add(v17, v13, ec, protocol.BGP);
        graph.add(v18, v13, ec, protocol.BGP);
        graph.add(v19, v14, ec, protocol.BGP);
        graph.add(v20, v14, ec, protocol.BGP);
        graph.add(v17, v15, ec, protocol.BGP);
        graph.add(v18, v15, ec, protocol.BGP);
        graph.add(v19, v16, ec, protocol.BGP);
        graph.add(v20, v16, ec, protocol.BGP);
        */

        /*
        graph.diAdd(v49, v17, ec, protocol.BGP);
        graph.diAdd(v49, v18, ec, protocol.BGP);
        graph.diAdd(v49, v19, ec, protocol.BGP);
        graph.diAdd(v49, v20, ec, protocol.BGP);
        graph.diAdd(v50, v17, ec, protocol.BGP);
        graph.diAdd(v50, v18, ec, protocol.BGP);
        graph.diAdd(v50, v19, ec, protocol.BGP);
        graph.diAdd(v50, v20, ec, protocol.BGP);
        graph.diAdd(v51, v17, ec, protocol.BGP);
        graph.diAdd(v51, v18, ec, protocol.BGP);
        graph.diAdd(v51, v19, ec, protocol.BGP);
        graph.diAdd(v51, v20, ec, protocol.BGP);
        graph.diAdd(v52, v17, ec, protocol.BGP);
        graph.diAdd(v52, v18, ec, protocol.BGP);
        graph.diAdd(v52, v19, ec, protocol.BGP);
        graph.diAdd(v52, v20, ec, protocol.BGP);
        graph.diAdd(v53, v21, ec, protocol.BGP);
        graph.diAdd(v53, v22, ec, protocol.BGP);
        graph.diAdd(v53, v23, ec, protocol.BGP);
        graph.diAdd(v53, v24, ec, protocol.BGP);
        graph.diAdd(v54, v21, ec, protocol.BGP);
        graph.diAdd(v54, v22, ec, protocol.BGP);
        graph.diAdd(v54, v23, ec, protocol.BGP);
        graph.diAdd(v54, v24, ec, protocol.BGP);
        graph.diAdd(v55, v21, ec, protocol.BGP);
        graph.diAdd(v55, v22, ec, protocol.BGP);
        graph.diAdd(v55, v23, ec, protocol.BGP);
        graph.diAdd(v55, v24, ec, protocol.BGP);
        graph.diAdd(v56, v21, ec, protocol.BGP);
        graph.diAdd(v56, v22, ec, protocol.BGP);
        graph.diAdd(v56, v23, ec, protocol.BGP);
        graph.diAdd(v56, v24, ec, protocol.BGP);
        graph.diAdd(v57, v25, ec, protocol.BGP);
        graph.diAdd(v57, v26, ec, protocol.BGP);
        graph.diAdd(v57, v27, ec, protocol.BGP);
        graph.diAdd(v57, v28, ec, protocol.BGP);
        graph.diAdd(v58, v25, ec, protocol.BGP);
        graph.diAdd(v58, v26, ec, protocol.BGP);
        graph.diAdd(v58, v27, ec, protocol.BGP);
        graph.diAdd(v58, v28, ec, protocol.BGP);
        graph.diAdd(v59, v25, ec, protocol.BGP);
        graph.diAdd(v59, v26, ec, protocol.BGP);
        graph.diAdd(v59, v27, ec, protocol.BGP);
        graph.diAdd(v59, v28, ec, protocol.BGP);
        graph.diAdd(v60, v25, ec, protocol.BGP);
        graph.diAdd(v60, v26, ec, protocol.BGP);
        graph.diAdd(v60, v27, ec, protocol.BGP);
        graph.diAdd(v60, v28, ec, protocol.BGP);
        graph.diAdd(v61, v29, ec, protocol.BGP);
        graph.diAdd(v61, v30, ec, protocol.BGP);
        graph.diAdd(v61, v31, ec, protocol.BGP);
        graph.diAdd(v61, v32, ec, protocol.BGP);
        graph.diAdd(v62, v29, ec, protocol.BGP);
        graph.diAdd(v62, v30, ec, protocol.BGP);
        graph.diAdd(v62, v31, ec, protocol.BGP);
        graph.diAdd(v62, v32, ec, protocol.BGP);
        graph.diAdd(v63, v29, ec, protocol.BGP);
        graph.diAdd(v63, v30, ec, protocol.BGP);
        graph.diAdd(v63, v31, ec, protocol.BGP);
        graph.diAdd(v63, v32, ec, protocol.BGP);
        graph.diAdd(v64, v29, ec, protocol.BGP);
        graph.diAdd(v64, v30, ec, protocol.BGP);
        graph.diAdd(v64, v31, ec, protocol.BGP);
        graph.diAdd(v64, v32, ec, protocol.BGP);
        graph.diAdd(v65, v33, ec, protocol.BGP);
        graph.diAdd(v65, v34, ec, protocol.BGP);
        graph.diAdd(v65, v35, ec, protocol.BGP);
        graph.diAdd(v65, v36, ec, protocol.BGP);
        graph.diAdd(v66, v33, ec, protocol.BGP);
        graph.diAdd(v66, v34, ec, protocol.BGP);
        graph.diAdd(v66, v35, ec, protocol.BGP);
        graph.diAdd(v66, v36, ec, protocol.BGP);
        graph.diAdd(v67, v33, ec, protocol.BGP);
        graph.diAdd(v67, v34, ec, protocol.BGP);
        graph.diAdd(v67, v35, ec, protocol.BGP);
        graph.diAdd(v67, v36, ec, protocol.BGP);
        graph.diAdd(v68, v33, ec, protocol.BGP);
        graph.diAdd(v68, v34, ec, protocol.BGP);
        graph.diAdd(v68, v35, ec, protocol.BGP);
        graph.diAdd(v68, v36, ec, protocol.BGP);
        graph.diAdd(v69, v37, ec, protocol.BGP);
        graph.diAdd(v69, v38, ec, protocol.BGP);
        graph.diAdd(v69, v39, ec, protocol.BGP);
        graph.diAdd(v69, v40, ec, protocol.BGP);
        graph.diAdd(v70, v37, ec, protocol.BGP);
        graph.diAdd(v70, v38, ec, protocol.BGP);
        graph.diAdd(v70, v39, ec, protocol.BGP);
        graph.diAdd(v70, v40, ec, protocol.BGP);
        graph.diAdd(v71, v37, ec, protocol.BGP);
        graph.diAdd(v71, v38, ec, protocol.BGP);
        graph.diAdd(v71, v39, ec, protocol.BGP);
        graph.diAdd(v71, v40, ec, protocol.BGP);
        graph.diAdd(v72, v37, ec, protocol.BGP);
        graph.diAdd(v72, v38, ec, protocol.BGP);
        graph.diAdd(v72, v39, ec, protocol.BGP);
        graph.diAdd(v72, v40, ec, protocol.BGP);
        graph.diAdd(v73, v41, ec, protocol.BGP);
        graph.diAdd(v73, v42, ec, protocol.BGP);
        graph.diAdd(v73, v43, ec, protocol.BGP);
        graph.diAdd(v73, v44, ec, protocol.BGP);
        graph.diAdd(v74, v41, ec, protocol.BGP);
        graph.diAdd(v74, v42, ec, protocol.BGP);
        graph.diAdd(v74, v43, ec, protocol.BGP);
        graph.diAdd(v74, v44, ec, protocol.BGP);
        graph.diAdd(v75, v41, ec, protocol.BGP);
        graph.diAdd(v75, v42, ec, protocol.BGP);
        graph.diAdd(v75, v43, ec, protocol.BGP);
        graph.diAdd(v75, v44, ec, protocol.BGP);
        graph.diAdd(v76, v41, ec, protocol.BGP);
        graph.diAdd(v76, v42, ec, protocol.BGP);
        graph.diAdd(v76, v43, ec, protocol.BGP);
        graph.diAdd(v76, v44, ec, protocol.BGP);
        graph.diAdd(v77, v45, ec, protocol.BGP);
        graph.diAdd(v77, v46, ec, protocol.BGP);
        graph.diAdd(v77, v47, ec, protocol.BGP);
        graph.diAdd(v77, v48, ec, protocol.BGP);
        graph.diAdd(v78, v45, ec, protocol.BGP);
        graph.diAdd(v78, v46, ec, protocol.BGP);
        graph.diAdd(v78, v47, ec, protocol.BGP);
        graph.diAdd(v78, v48, ec, protocol.BGP);
        graph.diAdd(v79, v45, ec, protocol.BGP);
        graph.diAdd(v79, v46, ec, protocol.BGP);
        graph.diAdd(v79, v47, ec, protocol.BGP);
        graph.diAdd(v79, v48, ec, protocol.BGP);
        graph.diAdd(v80, v45, ec, protocol.BGP);
        graph.diAdd(v80, v46, ec, protocol.BGP);
        graph.diAdd(v80, v47, ec, protocol.BGP);
        graph.diAdd(v80, v48, ec, protocol.BGP);
        graph.diAdd(v17, v1, ec, protocol.BGP);
        graph.diAdd(v17, v2, ec, protocol.BGP);
        graph.diAdd(v17, v3, ec, protocol.BGP);
        graph.diAdd(v17, v4, ec, protocol.BGP);
        graph.diAdd(v18, v5, ec, protocol.BGP);
        graph.diAdd(v18, v6, ec, protocol.BGP);
        graph.diAdd(v18, v7, ec, protocol.BGP);
        graph.diAdd(v18, v8, ec, protocol.BGP);
        graph.diAdd(v19, v9, ec, protocol.BGP);
        graph.diAdd(v19, v10, ec, protocol.BGP);
        graph.diAdd(v19, v11, ec, protocol.BGP);
        graph.diAdd(v19, v12, ec, protocol.BGP);
        graph.diAdd(v20, v13, ec, protocol.BGP);
        graph.diAdd(v20, v14, ec, protocol.BGP);
        graph.diAdd(v20, v15, ec, protocol.BGP);
        graph.diAdd(v20, v16, ec, protocol.BGP);
        graph.diAdd(v21, v1, ec, protocol.BGP);
        graph.diAdd(v21, v2, ec, protocol.BGP);
        graph.diAdd(v21, v3, ec, protocol.BGP);
        graph.diAdd(v21, v4, ec, protocol.BGP);
        graph.diAdd(v22, v5, ec, protocol.BGP);
        graph.diAdd(v22, v6, ec, protocol.BGP);
        graph.diAdd(v22, v7, ec, protocol.BGP);
        graph.diAdd(v22, v8, ec, protocol.BGP);
        graph.diAdd(v23, v9, ec, protocol.BGP);
        graph.diAdd(v23, v10, ec, protocol.BGP);
        graph.diAdd(v23, v11, ec, protocol.BGP);
        graph.diAdd(v23, v12, ec, protocol.BGP);
        graph.diAdd(v24, v13, ec, protocol.BGP);
        graph.diAdd(v24, v14, ec, protocol.BGP);
        graph.diAdd(v24, v15, ec, protocol.BGP);
        graph.diAdd(v24, v16, ec, protocol.BGP);
        graph.diAdd(v25, v1, ec, protocol.BGP);
        graph.diAdd(v25, v2, ec, protocol.BGP);
        graph.diAdd(v25, v3, ec, protocol.BGP);
        graph.diAdd(v25, v4, ec, protocol.BGP);
        graph.diAdd(v26, v5, ec, protocol.BGP);
        graph.diAdd(v26, v6, ec, protocol.BGP);
        graph.diAdd(v26, v7, ec, protocol.BGP);
        graph.diAdd(v26, v8, ec, protocol.BGP);
        graph.diAdd(v27, v9, ec, protocol.BGP);
        graph.diAdd(v27, v10, ec, protocol.BGP);
        graph.diAdd(v27, v11, ec, protocol.BGP);
        graph.diAdd(v27, v12, ec, protocol.BGP);
        graph.diAdd(v28, v13, ec, protocol.BGP);
        graph.diAdd(v28, v14, ec, protocol.BGP);
        graph.diAdd(v28, v15, ec, protocol.BGP);
        graph.diAdd(v28, v16, ec, protocol.BGP);
        graph.diAdd(v29, v1, ec, protocol.BGP);
        graph.diAdd(v29, v2, ec, protocol.BGP);
        graph.diAdd(v29, v3, ec, protocol.BGP);
        graph.diAdd(v29, v4, ec, protocol.BGP);
        graph.diAdd(v30, v5, ec, protocol.BGP);
        graph.diAdd(v30, v6, ec, protocol.BGP);
        graph.diAdd(v30, v7, ec, protocol.BGP);
        graph.diAdd(v30, v8, ec, protocol.BGP);
        graph.diAdd(v31, v9, ec, protocol.BGP);
        graph.diAdd(v31, v10, ec, protocol.BGP);
        graph.diAdd(v31, v11, ec, protocol.BGP);
        graph.diAdd(v31, v12, ec, protocol.BGP);
        graph.diAdd(v32, v13, ec, protocol.BGP);
        graph.diAdd(v32, v14, ec, protocol.BGP);
        graph.diAdd(v32, v15, ec, protocol.BGP);
        graph.diAdd(v32, v16, ec, protocol.BGP);
        graph.diAdd(v33, v1, ec, protocol.BGP);
        graph.diAdd(v33, v2, ec, protocol.BGP);
        graph.diAdd(v33, v3, ec, protocol.BGP);
        graph.diAdd(v33, v4, ec, protocol.BGP);
        graph.diAdd(v34, v5, ec, protocol.BGP);
        graph.diAdd(v34, v6, ec, protocol.BGP);
        graph.diAdd(v34, v7, ec, protocol.BGP);
        graph.diAdd(v34, v8, ec, protocol.BGP);
        graph.diAdd(v35, v9, ec, protocol.BGP);
        graph.diAdd(v35, v10, ec, protocol.BGP);
        graph.diAdd(v35, v11, ec, protocol.BGP);
        graph.diAdd(v35, v12, ec, protocol.BGP);
        graph.diAdd(v36, v13, ec, protocol.BGP);
        graph.diAdd(v36, v14, ec, protocol.BGP);
        graph.diAdd(v36, v15, ec, protocol.BGP);
        graph.diAdd(v36, v16, ec, protocol.BGP);
        graph.diAdd(v37, v1, ec, protocol.BGP);
        graph.diAdd(v37, v2, ec, protocol.BGP);
        graph.diAdd(v37, v3, ec, protocol.BGP);
        graph.diAdd(v37, v4, ec, protocol.BGP);
        graph.diAdd(v38, v5, ec, protocol.BGP);
        graph.diAdd(v38, v6, ec, protocol.BGP);
        graph.diAdd(v38, v7, ec, protocol.BGP);
        graph.diAdd(v38, v8, ec, protocol.BGP);
        graph.diAdd(v39, v9, ec, protocol.BGP);
        graph.diAdd(v39, v10, ec, protocol.BGP);
        graph.diAdd(v39, v11, ec, protocol.BGP);
        graph.diAdd(v39, v12, ec, protocol.BGP);
        graph.diAdd(v40, v13, ec, protocol.BGP);
        graph.diAdd(v40, v14, ec, protocol.BGP);
        graph.diAdd(v40, v15, ec, protocol.BGP);
        graph.diAdd(v40, v16, ec, protocol.BGP);
        graph.diAdd(v41, v1, ec, protocol.BGP);
        graph.diAdd(v41, v2, ec, protocol.BGP);
        graph.diAdd(v41, v3, ec, protocol.BGP);
        graph.diAdd(v41, v4, ec, protocol.BGP);
        graph.diAdd(v42, v5, ec, protocol.BGP);
        graph.diAdd(v42, v6, ec, protocol.BGP);
        graph.diAdd(v42, v7, ec, protocol.BGP);
        graph.diAdd(v42, v8, ec, protocol.BGP);
        graph.diAdd(v43, v9, ec, protocol.BGP);
        graph.diAdd(v43, v10, ec, protocol.BGP);
        graph.diAdd(v43, v11, ec, protocol.BGP);
        graph.diAdd(v43, v12, ec, protocol.BGP);
        graph.diAdd(v44, v13, ec, protocol.BGP);
        graph.diAdd(v44, v14, ec, protocol.BGP);
        graph.diAdd(v44, v15, ec, protocol.BGP);
        graph.diAdd(v44, v16, ec, protocol.BGP);
        graph.diAdd(v45, v1, ec, protocol.BGP);
        graph.diAdd(v45, v2, ec, protocol.BGP);
        graph.diAdd(v45, v3, ec, protocol.BGP);
        graph.diAdd(v45, v4, ec, protocol.BGP);
        graph.diAdd(v46, v5, ec, protocol.BGP);
        graph.diAdd(v46, v6, ec, protocol.BGP);
        graph.diAdd(v46, v7, ec, protocol.BGP);
        graph.diAdd(v46, v8, ec, protocol.BGP);
        graph.diAdd(v47, v9, ec, protocol.BGP);
        graph.diAdd(v47, v10, ec, protocol.BGP);
        graph.diAdd(v47, v11, ec, protocol.BGP);
        graph.diAdd(v47, v12, ec, protocol.BGP);
        graph.diAdd(v48, v13, ec, protocol.BGP);
        graph.diAdd(v48, v14, ec, protocol.BGP);
        graph.diAdd(v48, v15, ec, protocol.BGP);
        graph.diAdd(v48, v16, ec, protocol.BGP);
        */
        //*
        graph.diAdd(v1, v19, ec, protocol.BGP);
        graph.diAdd(v1, v20, ec, protocol.BGP);
        graph.diAdd(v1, v21, ec, protocol.BGP);
        graph.diAdd(v2, v19, ec, protocol.BGP);
        graph.diAdd(v2, v20, ec, protocol.BGP);
        graph.diAdd(v2, v21, ec, protocol.BGP);
        graph.diAdd(v3, v19, ec, protocol.BGP);
        graph.diAdd(v3, v20, ec, protocol.BGP);
        graph.diAdd(v3, v21, ec, protocol.BGP);
        graph.diAdd(v4, v22, ec, protocol.BGP);
        graph.diAdd(v4, v23, ec, protocol.BGP);
        graph.diAdd(v4, v24, ec, protocol.BGP);
        graph.diAdd(v5, v22, ec, protocol.BGP);
        graph.diAdd(v5, v23, ec, protocol.BGP);
        graph.diAdd(v5, v24, ec, protocol.BGP);
        graph.diAdd(v6, v22, ec, protocol.BGP);
        graph.diAdd(v6, v23, ec, protocol.BGP);
        graph.diAdd(v6, v24, ec, protocol.BGP);
        graph.diAdd(v7, v25, ec, protocol.BGP);
        graph.diAdd(v7, v26, ec, protocol.BGP);
        graph.diAdd(v7, v27, ec, protocol.BGP);
        graph.diAdd(v8, v25, ec, protocol.BGP);
        graph.diAdd(v8, v26, ec, protocol.BGP);
        graph.diAdd(v8, v27, ec, protocol.BGP);
        graph.diAdd(v9, v25, ec, protocol.BGP);
        graph.diAdd(v9, v26, ec, protocol.BGP);
        graph.diAdd(v9, v27, ec, protocol.BGP);
        graph.diAdd(v10, v28, ec, protocol.BGP);
        graph.diAdd(v10, v29, ec, protocol.BGP);
        graph.diAdd(v10, v30, ec, protocol.BGP);
        graph.diAdd(v11, v28, ec, protocol.BGP);
        graph.diAdd(v11, v29, ec, protocol.BGP);
        graph.diAdd(v11, v30, ec, protocol.BGP);
        graph.diAdd(v12, v28, ec, protocol.BGP);
        graph.diAdd(v12, v29, ec, protocol.BGP);
        graph.diAdd(v12, v30, ec, protocol.BGP);
        graph.diAdd(v13, v31, ec, protocol.BGP);
        graph.diAdd(v13, v32, ec, protocol.BGP);
        graph.diAdd(v13, v33, ec, protocol.BGP);
        graph.diAdd(v14, v31, ec, protocol.BGP);
        graph.diAdd(v14, v32, ec, protocol.BGP);
        graph.diAdd(v14, v33, ec, protocol.BGP);
        graph.diAdd(v15, v31, ec, protocol.BGP);
        graph.diAdd(v15, v32, ec, protocol.BGP);
        graph.diAdd(v15, v33, ec, protocol.BGP);
        graph.diAdd(v16, v34, ec, protocol.BGP);
        graph.diAdd(v16, v35, ec, protocol.BGP);
        graph.diAdd(v16, v36, ec, protocol.BGP);
        graph.diAdd(v17, v34, ec, protocol.BGP);
        graph.diAdd(v17, v35, ec, protocol.BGP);
        graph.diAdd(v17, v36, ec, protocol.BGP);
        graph.diAdd(v18, v34, ec, protocol.BGP);
        graph.diAdd(v18, v35, ec, protocol.BGP);
        graph.diAdd(v18, v36, ec, protocol.BGP);
        graph.diAdd(v19, v37, ec, protocol.BGP);
        graph.diAdd(v19, v38, ec, protocol.BGP);
        graph.diAdd(v19, v39, ec, protocol.BGP);
        graph.diAdd(v20, v40, ec, protocol.BGP);
        graph.diAdd(v20, v41, ec, protocol.BGP);
        graph.diAdd(v20, v42, ec, protocol.BGP);
        graph.diAdd(v21, v43, ec, protocol.BGP);
        graph.diAdd(v21, v44, ec, protocol.BGP);
        graph.diAdd(v21, v45, ec, protocol.BGP);
        graph.diAdd(v22, v37, ec, protocol.BGP);
        graph.diAdd(v22, v38, ec, protocol.BGP);
        graph.diAdd(v22, v39, ec, protocol.BGP);
        graph.diAdd(v23, v40, ec, protocol.BGP);
        graph.diAdd(v23, v41, ec, protocol.BGP);
        graph.diAdd(v23, v42, ec, protocol.BGP);
        graph.diAdd(v24, v43, ec, protocol.BGP);
        graph.diAdd(v24, v44, ec, protocol.BGP);
        graph.diAdd(v24, v45, ec, protocol.BGP);
        graph.diAdd(v25, v37, ec, protocol.BGP);
        graph.diAdd(v25, v38, ec, protocol.BGP);
        graph.diAdd(v25, v39, ec, protocol.BGP);
        graph.diAdd(v26, v40, ec, protocol.BGP);
        graph.diAdd(v26, v41, ec, protocol.BGP);
        graph.diAdd(v26, v42, ec, protocol.BGP);
        graph.diAdd(v27, v43, ec, protocol.BGP);
        graph.diAdd(v27, v44, ec, protocol.BGP);
        graph.diAdd(v27, v45, ec, protocol.BGP);
        graph.diAdd(v28, v37, ec, protocol.BGP);
        graph.diAdd(v28, v38, ec, protocol.BGP);
        graph.diAdd(v28, v39, ec, protocol.BGP);
        graph.diAdd(v29, v40, ec, protocol.BGP);
        graph.diAdd(v29, v41, ec, protocol.BGP);
        graph.diAdd(v29, v42, ec, protocol.BGP);
        graph.diAdd(v30, v43, ec, protocol.BGP);
        graph.diAdd(v30, v44, ec, protocol.BGP);
        graph.diAdd(v30, v45, ec, protocol.BGP);
        graph.diAdd(v31, v37, ec, protocol.BGP);
        graph.diAdd(v31, v38, ec, protocol.BGP);
        graph.diAdd(v31, v39, ec, protocol.BGP);
        graph.diAdd(v32, v40, ec, protocol.BGP);
        graph.diAdd(v32, v41, ec, protocol.BGP);
        graph.diAdd(v32, v42, ec, protocol.BGP);
        graph.diAdd(v33, v43, ec, protocol.BGP);
        graph.diAdd(v33, v44, ec, protocol.BGP);
        graph.diAdd(v33, v45, ec, protocol.BGP);
        graph.diAdd(v34, v37, ec, protocol.BGP);
        graph.diAdd(v34, v38, ec, protocol.BGP);
        graph.diAdd(v34, v39, ec, protocol.BGP);
        graph.diAdd(v35, v40, ec, protocol.BGP);
        graph.diAdd(v35, v41, ec, protocol.BGP);
        graph.diAdd(v35, v42, ec, protocol.BGP);
        graph.diAdd(v36, v43, ec, protocol.BGP);
        graph.diAdd(v36, v44, ec, protocol.BGP);
        graph.diAdd(v36, v45, ec, protocol.BGP);
        //*/

        //kconn.formulate(v1,v18);
        //kconn.formulate(v1,v8);
        //kconn.run();
        graph.setCommunity();
        long startTime = System.nanoTime();
        boolean b = vf.alwaysBlocked(v1,v18);//unreach.isUnreachable(v1,v18);

        //RYen y = new RYen(graph);
        //ArrayList<Path> k = y.ksp(v1, v18, 9);
        //KConnected kconn = new KConnected(graph);
        //kconn.formulate(v1, v18);
        //double time = kconn.run();
        //boolean b = vf.equalLength(v1,v18);
        long endTime = System.nanoTime();
        long duration = (endTime - startTime)/(1000000);
        //System.out.println("Paths " + k + " : " + duration + " ms");
        System.out.println("Always blocked? " + b);
        //System.out.println("Time : " + time + " ms");



    }
}